# LFishing v1.6.1.1
# https://github.com/karpen-dev/

# Supported only & colors and §

# Lang
# For example: en_US, ru_RU
lang: ru_RU

# Chances
# От 0.0 до 100.0 (в процентах)
chances:
  # Общий шанс того, что бокс вообще выпадет
  drop: 5.0

  default: 70.0
  normal: 20.0
  epic: 9.0
  legend: 1.0

  # Шанс поломки удочки
  break: 5.0

# Luck chances
luck:

  # Включить использование шансов из этой секции при наличии зачарования "Везучий рыбак"
  enabled: true

  default: 50.0
  normal: 30.0
  epic: 15.0
  legend: 5.0

# Skins
# Use https://textures.minecraft.net/texture/ only!
skin:
  default: "https://textures.minecraft.net/texture/2cf5b1cfed1c27dd4c3bef6b9844994739851e46b3fc7fda1cbc25b80ab3b"
  normal: "https://textures.minecraft.net/texture/f7145c0ee1cd493664fb1b26622db0492a1969a659931e7a3362d9071fbd4cf8"
  epic: "https://textures.minecraft.net/texture/a1b96fc7d915b57f683493106704353d8837772dff51b20bf3bda09f2fa8b3ba"
  legend: "https://textures.minecraft.net/texture/cdf81449131dcdd3578899fcd9592e13f5cca57ae7481fd6710bb6ca85d65c9"