name: LFishing
version: '2.0'
main: jp.karpen.lFishing.LFishing
api-version: '1.21'
commands:
  getbox:
    usage: /getbox <default | normal | epic>
    description: Give box
    permission: karpen.lfishing.getbox
    permission-message: You don't have permission